weights: yolov5x.pt
cfg: ''
data: data/coco128.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 3
batch_size: 6
imgsz: 512
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 300
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 1
project: runs/evolve
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/evolve/exp
