wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1634394177
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 19
      4: 3.8.10
      5: 0.12.4
      8:
      - 5
learning_rate:
  desc: null
  value: 0.01
