weights: yolov5x.pt
cfg: ''
data: data/coco128.yaml
hyp:
  lr0: 0.01
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.000515625
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.006250000000000001
  cls_pw: 1.0
  obj: 0.6400000000000001
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
  anchors: 3
  label_smoothing: 0.0
epochs: 20
batch_size: 6
imgsz: 512
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 300
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 1
project: runs/evolve
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: 2
artifact_alias: latest
save_dir: runs/evolve/exp2
